[package]
name = "freem"
version = "0.3.0"
edition = "2024"
description = "Memory check command"
license = "MIT"

[dependencies]
sysinfo = "0.35.2"

[profile.release]
codegen-units = 1
opt-level = "z"
panic = "abort"
strip = true
lto = true
